[package]
name = "thrustc_parser"
description.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
ahash = "0.8.11"
either = "1.15.0"

thrustc_entities = { path = "../thrustc_entities" }
thrustc_modificators = { path = "../thrustc_modificators" }
thrustc_mir = { path = "../thrustc_mir" }
thrustc_frontend_abort = { path = "../thrustc_frontend_abort" }
thrustc_attributes = { path = "../thrustc_attributes" }
thrustc_ast = { path = "../thrustc_ast" }
thrustc_typesystem = { path = "../thrustc_typesystem" }
thrustc_options = { path = "../thrustc_options" }
thrustc_diagnostician = { path = "../thrustc_diagnostician" }
thrustc_errors = { path = "../thrustc_errors" }
thrustc_span = { path = "../thrustc_span" }
thrustc_token = { path = "../thrustc_token" }
thrustc_logging = { path = "../thrustc_logging" }
thrustc_token_type = { path = "../thrustc_token_type" }
thrustc_constants = { path = "../thrustc_constants" }
thrustc_reader = { path = "../thrustc_reader" }
thrustc_lexer = { path = "../thrustc_lexer" }
