[package]
name = "thrustc_ast"
description.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
thrustc_span = { path = "../thrustc_span" }
thrustc_typesystem = { path = "../thrustc_typesystem" }
thrustc_attributes = { path = "../thrustc_attributes" }
thrustc_modificators = { path = "../thrustc_modificators" }
thrustc_mir = { path = "../thrustc_mir" }
thrustc_token = { path = "../thrustc_token" }
thrustc_errors = { path = "../thrustc_errors" }
thrustc_token_type = { path = "../thrustc_token_type" }

arbitrary =  { version = "1.4.2", features = ["derive"], optional = true }

[features]
fuzz = ["dep:arbitrary"]