[toolchain]
channel = "nightly"
components = ["rustfmt", "clippy"]

targets = [
    # Linux
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",

    # Windows
    "x86_64-pc-windows-gnu",
    "x86_64-pc-windows-msvc"
]