[package]
name = "thrustc_ast_verifier"
description.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
thrustc_token = { path = "../thrustc_token" }
thrustc_ast = { path = "../thrustc_ast" }
thrustc_entities = { path = "../thrustc_entities" }
thrustc_errors = { path = "../thrustc_errors" }
thrustc_options = { path = "../thrustc_options" }
thrustc_diagnostician = { path = "../thrustc_diagnostician" }
thrustc_logging = { path = "../thrustc_logging" }
thrustc_attributes = { path = "../thrustc_attributes" }
thrustc_span = { path = "../thrustc_span" }
thrustc_typesystem = { path = "../thrustc_typesystem" }
thrustc_token_type = { path = "../thrustc_token_type" }