[package]
name = "thrustc_preprocessor"
description.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
ahash = "0.8.11"
uuid = { version = "1.19.0", features = ["v4"] }

thrustc_logging = { path = "../thrustc_logging"  }
thrustc_reader = { path = "../thrustc_reader" }
thrustc_constants = { path = "../thrustc_constants" }
thrustc_frontend_abort = { path = "../thrustc_frontend_abort" }
thrustc_errors = { path = "../thrustc_errors" }
thrustc_options = { path = "../thrustc_options" }
thrustc_diagnostician = { path = "../thrustc_diagnostician" }
thrustc_span = { path = "../thrustc_span" }
thrustc_attributes = { path = "../thrustc_attributes" }
thrustc_typesystem = { path = "../thrustc_typesystem" }
thrustc_ast = { path = "../thrustc_ast" }
thrustc_token = { path = "../thrustc_token" }
thrustc_token_type = { path = "../thrustc_token_type" }
thrustc_lexer = { path = "../thrustc_lexer" }
