[package]
name = "thrustc_llvm_callconventions_checker"
description.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]

thrustc_llvm_callconventions = { path = "../thrustc_llvm_callconventions" }
thrustc_llvm_attributes = { path = "../thrustc_llvm_attributes"  } 
thrustc_attributes = { path = "../thrustc_attributes" } 
thrustc_options = { path = "../thrustc_options" }
thrustc_logging = { path = "../thrustc_logging" }
thrustc_diagnostician = { path = "../thrustc_diagnostician" }
thrustc_span = { path = "../thrustc_span" }
thrustc_ast = { path = "../thrustc_ast" }
thrustc_errors = { path = "../thrustc_errors" }