[build]
rustc-wrapper = "sccache"

rustflags = [
    "-A", "missing_abi",
    "-A", "dead_code",
    "-A", "clippy::enum_variant_names",
    "-A", "elided_lifetimes_in_paths",
    "-A", "clippy::new_without_default"
]

[lints.clippy]
style     = "allow"
complexity = "allow"
pedantic  = "allow"
new_without_default = "allow"