[package]
name = "thrustc_diagnostician" 
description.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
colored = "3.0.0"

thrustc_options = { path = "../thrustc_options" }
thrustc_logging = { path = "../thrustc_logging" }
thrustc_errors = { path = "../thrustc_errors" }
thrustc_span = { path = "../thrustc_span" }