[package]
name = "thrustc_core"
description.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
fastrand = "2.3.0"
either = "1.15.0"
colored = "3.0.0"

inkwell = { workspace = true, optional = true }
clang = { workspace = true, optional = true }

clipboard = { version = "0.5.0", optional = true }

thrustc_preprocessor = { path = "../thrustc_preprocessor" }
thrustc_llvm_callconventions_checker = { path = "../thrustc_llvm_callconventions_checker" }
thrustc_llvm_intrinsic_checker = { path = "../thrustc_llvm_intrinsic_checker" }
thrustc_constants = { path = "../thrustc_constants" }
thrustc_token = { path = "../thrustc_token" }
thrustc_diagnostician = { path = "../thrustc_diagnostician" }
thrustc_lexer = { path = "../thrustc_lexer" }
thrustc_parser = { path = "../thrustc_parser" }
thrustc_ast = { path = "../thrustc_ast" }
thrustc_options = { path = "../thrustc_options" }
thrustc_semantic = { path = "../thrustc_semantic" }
thrustc_llvm_codegen = { path = "../thrustc_llvm_codegen" }
thrustc_logging = { path = "../thrustc_logging" }

[features]
default = ["llvm_backend_static", "cbindgen_static", "utils"]

llvm_backend_dynamic = ["dep:inkwell", "inkwell/llvm17-0", "inkwell/llvm17-0-force-dynamic"]
llvm_backend_static  = ["dep:inkwell", "inkwell/llvm17-0", "inkwell/llvm17-0-force-static"]

cbindgen_static      = ["dep:clang", "clang/static"]
cbindgen_dynamic     = ["dep:clang"]

utils = ["dep:clipboard"]


