[package]
name = "thrustc_reader"
description.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1.0.102"
encoding_rs = "0.8.35"
encoding_rs_io = "0.1.7"
bytecount = "0.6.9"

thrustc_logging = { path = "../thrustc_logging" }